function tr = initHomogeneousTransforms(consts)

tr.fr_EpauleAVD_Xh_fr_base = zeros(4,4);
tr.fr_EpauleAVD_Xh_fr_base(1,1) = 0.0;
tr.fr_EpauleAVD_Xh_fr_base(2,1) = 0.0;
tr.fr_EpauleAVD_Xh_fr_base(3,1) = -1.0;
tr.fr_EpauleAVD_Xh_fr_base(3,2) = 0.0;
tr.fr_EpauleAVD_Xh_fr_base(3,3) = 0.0;
tr.fr_EpauleAVD_Xh_fr_base(3,4) =  consts.tx_rf_haa_joint;    % Maxima DSL: _k__tx_rf_haa_joint
tr.fr_EpauleAVD_Xh_fr_base(4,1) = 0.0;
tr.fr_EpauleAVD_Xh_fr_base(4,2) = 0.0;
tr.fr_EpauleAVD_Xh_fr_base(4,3) = 0.0;
tr.fr_EpauleAVD_Xh_fr_base(4,4) = 1.0;

tr.fr_base_Xh_fr_EpauleAVD = zeros(4,4);
tr.fr_base_Xh_fr_EpauleAVD(1,1) = 0.0;
tr.fr_base_Xh_fr_EpauleAVD(1,2) = 0.0;
tr.fr_base_Xh_fr_EpauleAVD(1,3) = -1.0;
tr.fr_base_Xh_fr_EpauleAVD(1,4) =  consts.tx_rf_haa_joint;    % Maxima DSL: _k__tx_rf_haa_joint
tr.fr_base_Xh_fr_EpauleAVD(2,3) = 0.0;
tr.fr_base_Xh_fr_EpauleAVD(2,4) =  consts.ty_rf_haa_joint;    % Maxima DSL: _k__ty_rf_haa_joint
tr.fr_base_Xh_fr_EpauleAVD(3,3) = 0.0;
tr.fr_base_Xh_fr_EpauleAVD(3,4) =  consts.tz_rf_haa_joint;    % Maxima DSL: _k__tz_rf_haa_joint
tr.fr_base_Xh_fr_EpauleAVD(4,1) = 0.0;
tr.fr_base_Xh_fr_EpauleAVD(4,2) = 0.0;
tr.fr_base_Xh_fr_EpauleAVD(4,3) = 0.0;
tr.fr_base_Xh_fr_EpauleAVD(4,4) = 1.0;

tr.fr_HJambeAVD_Xh_fr_EpauleAVD = zeros(4,4);
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(1,2) = 0.0;
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(1,4) = 0.0;
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(2,2) = 0.0;
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(2,4) = 0.0;
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(3,1) = 0.0;
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(3,2) = -1.0;
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(3,3) = 0.0;
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(3,4) =  consts.ty_rf_hfe_joint;    % Maxima DSL: _k__ty_rf_hfe_joint
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(4,1) = 0.0;
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(4,2) = 0.0;
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(4,3) = 0.0;
tr.fr_HJambeAVD_Xh_fr_EpauleAVD(4,4) = 1.0;

tr.fr_EpauleAVD_Xh_fr_HJambeAVD = zeros(4,4);
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(1,3) = 0.0;
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(1,4) = 0.0;
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(2,1) = 0.0;
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(2,2) = 0.0;
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(2,3) = -1.0;
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(2,4) =  consts.ty_rf_hfe_joint;    % Maxima DSL: _k__ty_rf_hfe_joint
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(3,3) = 0.0;
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(3,4) = 0.0;
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(4,1) = 0.0;
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(4,2) = 0.0;
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(4,3) = 0.0;
tr.fr_EpauleAVD_Xh_fr_HJambeAVD(4,4) = 1.0;

tr.fr_BJambeAVD_Xh_fr_HJambeAVD = zeros(4,4);
tr.fr_BJambeAVD_Xh_fr_HJambeAVD(1,3) = 0.0;
tr.fr_BJambeAVD_Xh_fr_HJambeAVD(2,3) = 0.0;
tr.fr_BJambeAVD_Xh_fr_HJambeAVD(3,1) = 0.0;
tr.fr_BJambeAVD_Xh_fr_HJambeAVD(3,2) = 0.0;
tr.fr_BJambeAVD_Xh_fr_HJambeAVD(3,3) = -1.0;
tr.fr_BJambeAVD_Xh_fr_HJambeAVD(3,4) = 0.0;
tr.fr_BJambeAVD_Xh_fr_HJambeAVD(4,1) = 0.0;
tr.fr_BJambeAVD_Xh_fr_HJambeAVD(4,2) = 0.0;
tr.fr_BJambeAVD_Xh_fr_HJambeAVD(4,3) = 0.0;
tr.fr_BJambeAVD_Xh_fr_HJambeAVD(4,4) = 1.0;

tr.fr_HJambeAVD_Xh_fr_BJambeAVD = zeros(4,4);
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(1,3) = 0.0;
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(1,4) =  consts.tx_rf_kfe_joint;    % Maxima DSL: _k__tx_rf_kfe_joint
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(2,3) = 0.0;
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(2,4) =  consts.ty_rf_kfe_joint;    % Maxima DSL: _k__ty_rf_kfe_joint
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(3,1) = 0.0;
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(3,2) = 0.0;
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(3,3) = -1.0;
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(3,4) = 0.0;
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(4,1) = 0.0;
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(4,2) = 0.0;
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(4,3) = 0.0;
tr.fr_HJambeAVD_Xh_fr_BJambeAVD(4,4) = 1.0;

tr.fr_EpauleAVG_Xh_fr_base = zeros(4,4);
tr.fr_EpauleAVG_Xh_fr_base(1,1) = 0.0;
tr.fr_EpauleAVG_Xh_fr_base(2,1) = 0.0;
tr.fr_EpauleAVG_Xh_fr_base(3,1) = 1.0;
tr.fr_EpauleAVG_Xh_fr_base(3,2) = 0.0;
tr.fr_EpauleAVG_Xh_fr_base(3,3) = 0.0;
tr.fr_EpauleAVG_Xh_fr_base(3,4) = - consts.tx_lf_haa_joint;    % Maxima DSL: -_k__tx_lf_haa_joint
tr.fr_EpauleAVG_Xh_fr_base(4,1) = 0.0;
tr.fr_EpauleAVG_Xh_fr_base(4,2) = 0.0;
tr.fr_EpauleAVG_Xh_fr_base(4,3) = 0.0;
tr.fr_EpauleAVG_Xh_fr_base(4,4) = 1.0;

tr.fr_base_Xh_fr_EpauleAVG = zeros(4,4);
tr.fr_base_Xh_fr_EpauleAVG(1,1) = 0.0;
tr.fr_base_Xh_fr_EpauleAVG(1,2) = 0.0;
tr.fr_base_Xh_fr_EpauleAVG(1,3) = 1.0;
tr.fr_base_Xh_fr_EpauleAVG(1,4) =  consts.tx_lf_haa_joint;    % Maxima DSL: _k__tx_lf_haa_joint
tr.fr_base_Xh_fr_EpauleAVG(2,3) = 0.0;
tr.fr_base_Xh_fr_EpauleAVG(2,4) =  consts.ty_lf_haa_joint;    % Maxima DSL: _k__ty_lf_haa_joint
tr.fr_base_Xh_fr_EpauleAVG(3,3) = 0.0;
tr.fr_base_Xh_fr_EpauleAVG(3,4) =  consts.tz_lf_haa_joint;    % Maxima DSL: _k__tz_lf_haa_joint
tr.fr_base_Xh_fr_EpauleAVG(4,1) = 0.0;
tr.fr_base_Xh_fr_EpauleAVG(4,2) = 0.0;
tr.fr_base_Xh_fr_EpauleAVG(4,3) = 0.0;
tr.fr_base_Xh_fr_EpauleAVG(4,4) = 1.0;

tr.fr_HJambeAVG_Xh_fr_EpauleAVG = zeros(4,4);
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(1,2) = 0.0;
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(1,4) = 0.0;
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(2,2) = 0.0;
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(2,4) = 0.0;
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(3,1) = 0.0;
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(3,2) = -1.0;
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(3,3) = 0.0;
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(3,4) =  consts.ty_lf_hfe_joint;    % Maxima DSL: _k__ty_lf_hfe_joint
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(4,1) = 0.0;
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(4,2) = 0.0;
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(4,3) = 0.0;
tr.fr_HJambeAVG_Xh_fr_EpauleAVG(4,4) = 1.0;

tr.fr_EpauleAVG_Xh_fr_HJambeAVG = zeros(4,4);
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(1,3) = 0.0;
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(1,4) = 0.0;
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(2,1) = 0.0;
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(2,2) = 0.0;
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(2,3) = -1.0;
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(2,4) =  consts.ty_lf_hfe_joint;    % Maxima DSL: _k__ty_lf_hfe_joint
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(3,3) = 0.0;
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(3,4) = 0.0;
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(4,1) = 0.0;
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(4,2) = 0.0;
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(4,3) = 0.0;
tr.fr_EpauleAVG_Xh_fr_HJambeAVG(4,4) = 1.0;

tr.fr_BJambeAVG_Xh_fr_HJambeAVG = zeros(4,4);
tr.fr_BJambeAVG_Xh_fr_HJambeAVG(1,3) = 0.0;
tr.fr_BJambeAVG_Xh_fr_HJambeAVG(2,3) = 0.0;
tr.fr_BJambeAVG_Xh_fr_HJambeAVG(3,1) = 0.0;
tr.fr_BJambeAVG_Xh_fr_HJambeAVG(3,2) = 0.0;
tr.fr_BJambeAVG_Xh_fr_HJambeAVG(3,3) = -1.0;
tr.fr_BJambeAVG_Xh_fr_HJambeAVG(3,4) = 0.0;
tr.fr_BJambeAVG_Xh_fr_HJambeAVG(4,1) = 0.0;
tr.fr_BJambeAVG_Xh_fr_HJambeAVG(4,2) = 0.0;
tr.fr_BJambeAVG_Xh_fr_HJambeAVG(4,3) = 0.0;
tr.fr_BJambeAVG_Xh_fr_HJambeAVG(4,4) = 1.0;

tr.fr_HJambeAVG_Xh_fr_BJambeAVG = zeros(4,4);
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(1,3) = 0.0;
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(1,4) =  consts.tx_lf_kfe_joint;    % Maxima DSL: _k__tx_lf_kfe_joint
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(2,3) = 0.0;
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(2,4) =  consts.ty_lf_kfe_joint;    % Maxima DSL: _k__ty_lf_kfe_joint
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(3,1) = 0.0;
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(3,2) = 0.0;
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(3,3) = -1.0;
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(3,4) = 0.0;
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(4,1) = 0.0;
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(4,2) = 0.0;
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(4,3) = 0.0;
tr.fr_HJambeAVG_Xh_fr_BJambeAVG(4,4) = 1.0;

tr.fr_EpauleARD_Xh_fr_base = zeros(4,4);
tr.fr_EpauleARD_Xh_fr_base(1,1) = 0.0;
tr.fr_EpauleARD_Xh_fr_base(2,1) = 0.0;
tr.fr_EpauleARD_Xh_fr_base(3,1) = -1.0;
tr.fr_EpauleARD_Xh_fr_base(3,2) = 0.0;
tr.fr_EpauleARD_Xh_fr_base(3,3) = 0.0;
tr.fr_EpauleARD_Xh_fr_base(3,4) =  consts.tx_rh_haa_joint;    % Maxima DSL: _k__tx_rh_haa_joint
tr.fr_EpauleARD_Xh_fr_base(4,1) = 0.0;
tr.fr_EpauleARD_Xh_fr_base(4,2) = 0.0;
tr.fr_EpauleARD_Xh_fr_base(4,3) = 0.0;
tr.fr_EpauleARD_Xh_fr_base(4,4) = 1.0;

tr.fr_base_Xh_fr_EpauleARD = zeros(4,4);
tr.fr_base_Xh_fr_EpauleARD(1,1) = 0.0;
tr.fr_base_Xh_fr_EpauleARD(1,2) = 0.0;
tr.fr_base_Xh_fr_EpauleARD(1,3) = -1.0;
tr.fr_base_Xh_fr_EpauleARD(1,4) =  consts.tx_rh_haa_joint;    % Maxima DSL: _k__tx_rh_haa_joint
tr.fr_base_Xh_fr_EpauleARD(2,3) = 0.0;
tr.fr_base_Xh_fr_EpauleARD(2,4) =  consts.ty_rh_haa_joint;    % Maxima DSL: _k__ty_rh_haa_joint
tr.fr_base_Xh_fr_EpauleARD(3,3) = 0.0;
tr.fr_base_Xh_fr_EpauleARD(3,4) =  consts.tz_rh_haa_joint;    % Maxima DSL: _k__tz_rh_haa_joint
tr.fr_base_Xh_fr_EpauleARD(4,1) = 0.0;
tr.fr_base_Xh_fr_EpauleARD(4,2) = 0.0;
tr.fr_base_Xh_fr_EpauleARD(4,3) = 0.0;
tr.fr_base_Xh_fr_EpauleARD(4,4) = 1.0;

tr.fr_HJambeARD_Xh_fr_EpauleARD = zeros(4,4);
tr.fr_HJambeARD_Xh_fr_EpauleARD(1,2) = 0.0;
tr.fr_HJambeARD_Xh_fr_EpauleARD(1,4) = 0.0;
tr.fr_HJambeARD_Xh_fr_EpauleARD(2,2) = 0.0;
tr.fr_HJambeARD_Xh_fr_EpauleARD(2,4) = 0.0;
tr.fr_HJambeARD_Xh_fr_EpauleARD(3,1) = 0.0;
tr.fr_HJambeARD_Xh_fr_EpauleARD(3,2) = -1.0;
tr.fr_HJambeARD_Xh_fr_EpauleARD(3,3) = 0.0;
tr.fr_HJambeARD_Xh_fr_EpauleARD(3,4) =  consts.ty_rh_hfe_joint;    % Maxima DSL: _k__ty_rh_hfe_joint
tr.fr_HJambeARD_Xh_fr_EpauleARD(4,1) = 0.0;
tr.fr_HJambeARD_Xh_fr_EpauleARD(4,2) = 0.0;
tr.fr_HJambeARD_Xh_fr_EpauleARD(4,3) = 0.0;
tr.fr_HJambeARD_Xh_fr_EpauleARD(4,4) = 1.0;

tr.fr_EpauleARD_Xh_fr_HJambeARD = zeros(4,4);
tr.fr_EpauleARD_Xh_fr_HJambeARD(1,3) = 0.0;
tr.fr_EpauleARD_Xh_fr_HJambeARD(1,4) = 0.0;
tr.fr_EpauleARD_Xh_fr_HJambeARD(2,1) = 0.0;
tr.fr_EpauleARD_Xh_fr_HJambeARD(2,2) = 0.0;
tr.fr_EpauleARD_Xh_fr_HJambeARD(2,3) = -1.0;
tr.fr_EpauleARD_Xh_fr_HJambeARD(2,4) =  consts.ty_rh_hfe_joint;    % Maxima DSL: _k__ty_rh_hfe_joint
tr.fr_EpauleARD_Xh_fr_HJambeARD(3,3) = 0.0;
tr.fr_EpauleARD_Xh_fr_HJambeARD(3,4) = 0.0;
tr.fr_EpauleARD_Xh_fr_HJambeARD(4,1) = 0.0;
tr.fr_EpauleARD_Xh_fr_HJambeARD(4,2) = 0.0;
tr.fr_EpauleARD_Xh_fr_HJambeARD(4,3) = 0.0;
tr.fr_EpauleARD_Xh_fr_HJambeARD(4,4) = 1.0;

tr.fr_BJambeARD_Xh_fr_HJambeARD = zeros(4,4);
tr.fr_BJambeARD_Xh_fr_HJambeARD(1,3) = 0.0;
tr.fr_BJambeARD_Xh_fr_HJambeARD(2,3) = 0.0;
tr.fr_BJambeARD_Xh_fr_HJambeARD(3,1) = 0.0;
tr.fr_BJambeARD_Xh_fr_HJambeARD(3,2) = 0.0;
tr.fr_BJambeARD_Xh_fr_HJambeARD(3,3) = -1.0;
tr.fr_BJambeARD_Xh_fr_HJambeARD(3,4) = 0.0;
tr.fr_BJambeARD_Xh_fr_HJambeARD(4,1) = 0.0;
tr.fr_BJambeARD_Xh_fr_HJambeARD(4,2) = 0.0;
tr.fr_BJambeARD_Xh_fr_HJambeARD(4,3) = 0.0;
tr.fr_BJambeARD_Xh_fr_HJambeARD(4,4) = 1.0;

tr.fr_HJambeARD_Xh_fr_BJambeARD = zeros(4,4);
tr.fr_HJambeARD_Xh_fr_BJambeARD(1,3) = 0.0;
tr.fr_HJambeARD_Xh_fr_BJambeARD(1,4) =  consts.tx_rh_kfe_joint;    % Maxima DSL: _k__tx_rh_kfe_joint
tr.fr_HJambeARD_Xh_fr_BJambeARD(2,3) = 0.0;
tr.fr_HJambeARD_Xh_fr_BJambeARD(2,4) =  consts.ty_rh_kfe_joint;    % Maxima DSL: _k__ty_rh_kfe_joint
tr.fr_HJambeARD_Xh_fr_BJambeARD(3,1) = 0.0;
tr.fr_HJambeARD_Xh_fr_BJambeARD(3,2) = 0.0;
tr.fr_HJambeARD_Xh_fr_BJambeARD(3,3) = -1.0;
tr.fr_HJambeARD_Xh_fr_BJambeARD(3,4) = 0.0;
tr.fr_HJambeARD_Xh_fr_BJambeARD(4,1) = 0.0;
tr.fr_HJambeARD_Xh_fr_BJambeARD(4,2) = 0.0;
tr.fr_HJambeARD_Xh_fr_BJambeARD(4,3) = 0.0;
tr.fr_HJambeARD_Xh_fr_BJambeARD(4,4) = 1.0;

tr.fr_EpauleARG_Xh_fr_base = zeros(4,4);
tr.fr_EpauleARG_Xh_fr_base(1,1) = 0.0;
tr.fr_EpauleARG_Xh_fr_base(2,1) = 0.0;
tr.fr_EpauleARG_Xh_fr_base(3,1) = 1.0;
tr.fr_EpauleARG_Xh_fr_base(3,2) = 0.0;
tr.fr_EpauleARG_Xh_fr_base(3,3) = 0.0;
tr.fr_EpauleARG_Xh_fr_base(3,4) = - consts.tx_lh_haa_joint;    % Maxima DSL: -_k__tx_lh_haa_joint
tr.fr_EpauleARG_Xh_fr_base(4,1) = 0.0;
tr.fr_EpauleARG_Xh_fr_base(4,2) = 0.0;
tr.fr_EpauleARG_Xh_fr_base(4,3) = 0.0;
tr.fr_EpauleARG_Xh_fr_base(4,4) = 1.0;

tr.fr_base_Xh_fr_EpauleARG = zeros(4,4);
tr.fr_base_Xh_fr_EpauleARG(1,1) = 0.0;
tr.fr_base_Xh_fr_EpauleARG(1,2) = 0.0;
tr.fr_base_Xh_fr_EpauleARG(1,3) = 1.0;
tr.fr_base_Xh_fr_EpauleARG(1,4) =  consts.tx_lh_haa_joint;    % Maxima DSL: _k__tx_lh_haa_joint
tr.fr_base_Xh_fr_EpauleARG(2,3) = 0.0;
tr.fr_base_Xh_fr_EpauleARG(2,4) =  consts.ty_lh_haa_joint;    % Maxima DSL: _k__ty_lh_haa_joint
tr.fr_base_Xh_fr_EpauleARG(3,3) = 0.0;
tr.fr_base_Xh_fr_EpauleARG(3,4) =  consts.tz_lh_haa_joint;    % Maxima DSL: _k__tz_lh_haa_joint
tr.fr_base_Xh_fr_EpauleARG(4,1) = 0.0;
tr.fr_base_Xh_fr_EpauleARG(4,2) = 0.0;
tr.fr_base_Xh_fr_EpauleARG(4,3) = 0.0;
tr.fr_base_Xh_fr_EpauleARG(4,4) = 1.0;

tr.fr_HJambeARG_Xh_fr_EpauleARG = zeros(4,4);
tr.fr_HJambeARG_Xh_fr_EpauleARG(1,2) = 0.0;
tr.fr_HJambeARG_Xh_fr_EpauleARG(1,4) = 0.0;
tr.fr_HJambeARG_Xh_fr_EpauleARG(2,2) = 0.0;
tr.fr_HJambeARG_Xh_fr_EpauleARG(2,4) = 0.0;
tr.fr_HJambeARG_Xh_fr_EpauleARG(3,1) = 0.0;
tr.fr_HJambeARG_Xh_fr_EpauleARG(3,2) = -1.0;
tr.fr_HJambeARG_Xh_fr_EpauleARG(3,3) = 0.0;
tr.fr_HJambeARG_Xh_fr_EpauleARG(3,4) =  consts.ty_lh_hfe_joint;    % Maxima DSL: _k__ty_lh_hfe_joint
tr.fr_HJambeARG_Xh_fr_EpauleARG(4,1) = 0.0;
tr.fr_HJambeARG_Xh_fr_EpauleARG(4,2) = 0.0;
tr.fr_HJambeARG_Xh_fr_EpauleARG(4,3) = 0.0;
tr.fr_HJambeARG_Xh_fr_EpauleARG(4,4) = 1.0;

tr.fr_EpauleARG_Xh_fr_HJambeARG = zeros(4,4);
tr.fr_EpauleARG_Xh_fr_HJambeARG(1,3) = 0.0;
tr.fr_EpauleARG_Xh_fr_HJambeARG(1,4) = 0.0;
tr.fr_EpauleARG_Xh_fr_HJambeARG(2,1) = 0.0;
tr.fr_EpauleARG_Xh_fr_HJambeARG(2,2) = 0.0;
tr.fr_EpauleARG_Xh_fr_HJambeARG(2,3) = -1.0;
tr.fr_EpauleARG_Xh_fr_HJambeARG(2,4) =  consts.ty_lh_hfe_joint;    % Maxima DSL: _k__ty_lh_hfe_joint
tr.fr_EpauleARG_Xh_fr_HJambeARG(3,3) = 0.0;
tr.fr_EpauleARG_Xh_fr_HJambeARG(3,4) = 0.0;
tr.fr_EpauleARG_Xh_fr_HJambeARG(4,1) = 0.0;
tr.fr_EpauleARG_Xh_fr_HJambeARG(4,2) = 0.0;
tr.fr_EpauleARG_Xh_fr_HJambeARG(4,3) = 0.0;
tr.fr_EpauleARG_Xh_fr_HJambeARG(4,4) = 1.0;

tr.fr_BJambeARG_Xh_fr_HJambeARG = zeros(4,4);
tr.fr_BJambeARG_Xh_fr_HJambeARG(1,3) = 0.0;
tr.fr_BJambeARG_Xh_fr_HJambeARG(2,3) = 0.0;
tr.fr_BJambeARG_Xh_fr_HJambeARG(3,1) = 0.0;
tr.fr_BJambeARG_Xh_fr_HJambeARG(3,2) = 0.0;
tr.fr_BJambeARG_Xh_fr_HJambeARG(3,3) = -1.0;
tr.fr_BJambeARG_Xh_fr_HJambeARG(3,4) = 0.0;
tr.fr_BJambeARG_Xh_fr_HJambeARG(4,1) = 0.0;
tr.fr_BJambeARG_Xh_fr_HJambeARG(4,2) = 0.0;
tr.fr_BJambeARG_Xh_fr_HJambeARG(4,3) = 0.0;
tr.fr_BJambeARG_Xh_fr_HJambeARG(4,4) = 1.0;

tr.fr_HJambeARG_Xh_fr_BJambeARG = zeros(4,4);
tr.fr_HJambeARG_Xh_fr_BJambeARG(1,3) = 0.0;
tr.fr_HJambeARG_Xh_fr_BJambeARG(1,4) =  consts.tx_lh_kfe_joint;    % Maxima DSL: _k__tx_lh_kfe_joint
tr.fr_HJambeARG_Xh_fr_BJambeARG(2,3) = 0.0;
tr.fr_HJambeARG_Xh_fr_BJambeARG(2,4) =  consts.ty_lh_kfe_joint;    % Maxima DSL: _k__ty_lh_kfe_joint
tr.fr_HJambeARG_Xh_fr_BJambeARG(3,1) = 0.0;
tr.fr_HJambeARG_Xh_fr_BJambeARG(3,2) = 0.0;
tr.fr_HJambeARG_Xh_fr_BJambeARG(3,3) = -1.0;
tr.fr_HJambeARG_Xh_fr_BJambeARG(3,4) = 0.0;
tr.fr_HJambeARG_Xh_fr_BJambeARG(4,1) = 0.0;
tr.fr_HJambeARG_Xh_fr_BJambeARG(4,2) = 0.0;
tr.fr_HJambeARG_Xh_fr_BJambeARG(4,3) = 0.0;
tr.fr_HJambeARG_Xh_fr_BJambeARG(4,4) = 1.0;

