%% All the parameters of the robot popi
%%
%% OUT = MODELPARAMETERS()
%%
%% OUT is a structure with a field for each parameter of the robot.
%%
%% This file was automatically generated by RobCoGen.

function out = modelParameters()

warning('The model parameters have not been initialized; please modify this file with suitable initial values');
